from django.shortcuts import redirect

def redirect_to_tournaments(request, *args, **kwargs):
    return redirect('/astro/tournaments')

manage = redirect_to_tournaments
tournament_details_round_robin = redirect_to_tournaments
tournament_details_single_elimination = redirect_to_tournaments
tournament_details_double_elimination = redirect_to_tournaments
tournament_details_ladder = redirect_to_tournaments
tournament_details_swiss = redirect_to_tournaments
tournament_details_americano = redirect_to_tournaments
create_tournament = redirect_to_tournaments
edit_tournament = redirect_to_tournaments
edit_roundrobin_config = redirect_to_tournaments
edit_elimination_config = redirect_to_tournaments
edit_ladder_config = redirect_to_tournaments
edit_swiss_config = redirect_to_tournaments
edit_americano_config = redirect_to_tournaments
list_participants = redirect_to_tournaments
register_participant = redirect_to_tournaments
edit_participant = redirect_to_tournaments
add_team_member = redirect_to_tournaments
remove_team_member = redirect_to_tournaments
request_join = redirect_to_tournaments
approve_participant = redirect_to_tournaments
reject_participant = redirect_to_tournaments
remove_participant = redirect_to_tournaments
revert_to_draft = redirect_to_tournaments
open_registration = redirect_to_tournaments
close_registration = redirect_to_tournaments
start_tournament = redirect_to_tournaments
finish_tournament = redirect_to_tournaments
delete_tournament = redirect_to_tournaments
manage_matches = redirect_to_tournaments
generate_matches = redirect_to_tournaments
create_match = redirect_to_tournaments
edit_match = redirect_to_tournaments
live_match_view = redirect_to_tournaments
start_match = redirect_to_tournaments
delete_match = redirect_to_tournaments
reset_leaderboard_locks = redirect_to_tournaments
create_challenge_match = redirect_to_tournaments
cancel_challenge = redirect_to_tournaments
add_reaction = redirect_to_tournaments
