# Generated by Django 5.2.6 on 2025-09-27 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateTimeField(blank=True, help_text='Oficjalna data i godzina rozpoczęcia turnieju.', null=True)),
                ('end_date', models.DateTimeField(blank=True, help_text='Oficjalna data i godzina zakończenia turnieju.', null=True)),
                ('tournament_type', models.CharField(choices=[('SGL', 'Single Elimination'), ('DBL', 'Double Elimination'), ('RND', 'Round Robin'), ('LDR', 'Ladder')], default='RND', help_text='Format w jakim odbywają się rozgrywki.', max_length=3)),
                ('match_format', models.CharField(choices=[('SNG', 'Singiel (1 vs 1)'), ('DBL', 'Debel (2 vs 2)')], default='SNG', help_text='Liczba graczy biorących udział w pojedynczym spotkaniu.', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournaments_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Tournaments',
                'db_table': 'tournaments',
                'ordering': ['-created_at'],
            },
        ),
    ]
