# Generated by Django 5.2.6 on 2025-09-27 15:23

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EliminationConfig',
            fields=[
                ('max_participants', models.IntegerField(default=16, help_text='Maksymalna liczba graczy/zespołów.')),
                ('sets_to_win', models.IntegerField(default=2, help_text='Liczba setów, które należy wygrać, aby wygrać mecz (np. 1 z 2 lub 2 z 3).')),
                ('games_per_set', models.IntegerField(default=6, help_text='Liczba gemów wymaganych do wygrania seta (standardowo do 6 gemów z przewagą 2).')),
                ('tournament', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='elimination_config', serialize=False, to='tournaments.tournament')),
                ('is_seeded', models.BooleanField(default=False, help_text='Czy uczestnicy są rozstawiani w drabince (seeded).')),
                ('third_place_match', models.BooleanField(default=True, help_text='Czy ma być rozgrywany mecz o trzecie miejsce.')),
            ],
            options={
                'verbose_name': 'Konfiguracja Eliminacji',
                'verbose_name_plural': 'Konfiguracje Eliminacji',
            },
        ),
        migrations.CreateModel(
            name='RoundRobinConfig',
            fields=[
                ('max_participants', models.IntegerField(default=16, help_text='Maksymalna liczba graczy/zespołów.')),
                ('sets_to_win', models.IntegerField(default=2, help_text='Liczba setów, które należy wygrać, aby wygrać mecz (np. 1 z 2 lub 2 z 3).')),
                ('games_per_set', models.IntegerField(default=6, help_text='Liczba gemów wymaganych do wygrania seta (standardowo do 6 gemów z przewagą 2).')),
                ('tournament', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='round_robin_config', serialize=False, to='tournaments.tournament')),
                ('points_for_win', models.IntegerField(default=3, help_text='Liczba punktów za wygrany mecz.')),
                ('points_for_loss', models.IntegerField(default=0, help_text='Liczba punktów za przegrany mecz.')),
                ('points_for_set_win', models.IntegerField(default=1, help_text='Liczba punktów za wygrany set.')),
                ('points_for_gem_win', models.DecimalField(decimal_places=2, default=Decimal('0.1'), help_text='Liczba punktów za wygrany gem.', max_digits=3)),
                ('points_for_gem_loss', models.DecimalField(decimal_places=2, default=Decimal('-0.1'), help_text='Liczba punktów za przegrany gem.', max_digits=3)),
                ('points_for_supertiebreak_win', models.DecimalField(decimal_places=2, default=Decimal('0.05'), help_text='Liczba punktów za wygrany super tie-break.', max_digits=3)),
                ('points_for_supertiebreak_loss', models.DecimalField(decimal_places=2, default=Decimal('-0.05'), help_text='Liczba punktów za przegrany super tie-breakt.', max_digits=3)),
                ('tie_breaker_priority', models.CharField(choices=[('HEAD', 'Bezpośrednie spotkanie'), ('SETS', 'Bilans setów'), ('GAMES', 'Bilans gemów')], default='HEAD', help_text='Główne kryterium decydujące o kolejności w przypadku równej liczby punktów.', max_length=5)),
            ],
            options={
                'verbose_name': 'Konfiguracja Round Robin',
                'verbose_name_plural': 'Konfiguracje Round Robin',
            },
        ),
    ]
