# Generated by Django 5.2.6 on 2025-09-27 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_eliminationconfig_roundrobinconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='active',
        ),
        migrations.AddField(
            model_name='tournament',
            name='status',
            field=models.CharField(choices=[('DRF', 'Nieaktywny/Szkic'), ('REG', 'Oczekuje na graczy (Rejestracja otwarta)'), ('SCH', 'Zaplanowany (Rejestracja zamknięta)'), ('ACT', 'Rozpoczęty'), ('FIN', 'Zakończony'), ('CNC', 'Odwołany')], default='DRF', help_text='Aktualny stan i faza turnieju.', max_length=3),
        ),
    ]
