# Generated by Django 5.2.6 on 2025-09-27 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_remove_tournament_active_tournament_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(help_text='Nazwa wyświetlana w drabince/tabeli turnieju.', max_length=100)),
                ('seed_number', models.PositiveIntegerField(blank=True, help_text='Numer rozstawienia (seeding) w turnieju, jeśli dotyczy.', null=True)),
                ('status', models.CharField(choices=[('REG', 'Zarejestrowany'), ('ACT', 'Aktywny w rozgrywkach'), ('OUT', 'Wyeliminowany'), ('WDN', 'Wycofany'), ('BYE', 'Wolny los (Bye)')], default='REG', help_text='Status uczestnika w tym turnieju.', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tournament', models.ForeignKey(help_text='Turniej, do którego należy to zgłoszenie.', on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='tournaments.tournament')),
                ('user', models.ForeignKey(blank=True, help_text='Konto użytkownika głównego. Może być puste, jeśli jest to zespół zewnętrzny.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Uczestnik Turnieju',
                'verbose_name_plural': 'Uczestnicy Turnieju',
                'db_table': 'tournament_participants',
                'unique_together': {('tournament', 'display_name')},
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant', models.ForeignKey(help_text='Zgłoszenie zespołu, do którego należy ten członek.', on_delete=django.db.models.deletion.CASCADE, related_name='members', to='tournaments.participant')),
                ('user', models.ForeignKey(help_text='Konto użytkownika wchodzące w skład zespołu.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Członek Zespołu',
                'verbose_name_plural': 'Członkowie Zespołów',
                'unique_together': {('participant', 'user')},
            },
        ),
    ]
