# Generated by Django 5.2.6 on 2025-09-27 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_participant_teammember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='status',
            field=models.CharField(choices=[('PEN', 'Oczekuje na zatwierdzenie'), ('REG', 'Zarejestrowany'), ('ACT', 'Aktywny w rozgrywkach'), ('OUT', 'Wyeliminowany'), ('WDN', 'Wycofany'), ('BYE', 'Wolny los (Bye)')], default='REG', help_text='Status uczestnika w tym turnieju.', max_length=3),
        ),
    ]
