# Generated by Django 5.2.6 on 2025-09-28 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_alter_participant_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentsMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField(default=1, help_text='Numer rundy/etapu (np. Runda 1, Półfinał, Faza grupowa).')),
                ('match_index', models.PositiveIntegerField(default=1, help_text='Indeks meczu w danej rundzie (np. Mecz 1, Mecz 2).')),
                ('status', models.CharField(choices=[('SCH', 'Zaplanowany'), ('INP', 'W trakcie'), ('CMP', 'Zakończony'), ('WDR', 'Wycofany/Walkower'), ('CNC', 'Odwołany')], default='SCH', help_text='Status aktualnej rozgrywki.', max_length=3)),
                ('set1_p1_score', models.PositiveSmallIntegerField(blank=True, help_text='Liczba gemów Ucz. 1 w Secie 1.', null=True)),
                ('set1_p2_score', models.PositiveSmallIntegerField(blank=True, help_text='Liczba gemów Ucz. 2 w Secie 1.', null=True)),
                ('set2_p1_score', models.PositiveSmallIntegerField(blank=True, help_text='Liczba gemów Ucz. 1 w Secie 2.', null=True)),
                ('set2_p2_score', models.PositiveSmallIntegerField(blank=True, help_text='Liczba gemów Ucz. 2 w Secie 2.', null=True)),
                ('set3_p1_score', models.PositiveSmallIntegerField(blank=True, help_text='Liczba gemów Ucz. 1 w Secie 3.', null=True)),
                ('set3_p2_score', models.PositiveSmallIntegerField(blank=True, help_text='Liczba gemów Ucz. 2 w Secie 3.', null=True)),
                ('scheduled_time', models.DateTimeField(blank=True, help_text='Planowana data i godzina rozpoczęcia meczu.', null=True)),
                ('participant1', models.ForeignKey(blank=True, help_text='Pierwszy uczestnik/zespół.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_p1', to='tournaments.participant')),
                ('participant2', models.ForeignKey(blank=True, help_text='Drugi uczestnik/zespół.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_p2', to='tournaments.participant')),
                ('tournament', models.ForeignKey(help_text='Turniej, do którego należy mecz.', on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tournaments.tournament')),
                ('winner', models.ForeignKey(blank=True, help_text='Zwycięzca meczu.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_matches', to='tournaments.participant')),
            ],
            options={
                'verbose_name': 'Mecz Turniejowy',
                'verbose_name_plural': 'Mecze Turniejowe',
                'db_table': 'tournament_matches',
                'ordering': ['round_number', 'match_index'],
                'unique_together': {('tournament', 'round_number', 'match_index')},
            },
        ),
    ]
