# Generated by Django 5.2.6 on 2025-10-14 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0006_tournamentsmatch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tournament',
            options={'ordering': ['-created_at'], 'verbose_name': 'Turniej', 'verbose_name_plural': 'Turnieje'},
        ),
        migrations.AlterField(
            model_name='tournament',
            name='created_by',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.PROTECT, related_name='created_tournaments', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
