# Generated by Django 5.2.6 on 2025-10-22 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0007_alter_tournament_options_alter_tournament_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='LadderConfig',
            fields=[
                ('max_participants', models.IntegerField(default=16, help_text='Maksymalna liczba graczy/zespołów.')),
                ('sets_to_win', models.IntegerField(default=2, help_text='Liczba setów, które należy wygrać, aby wygrać mecz (np. 1 z 2 lub 2 z 3).')),
                ('games_per_set', models.IntegerField(default=6, help_text='Liczba gemów wymaganych do wygrania seta (standardowo do 6 gemów z przewagą 2).')),
                ('tournament', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='ladder_config', serialize=False, to='tournaments.tournament')),
                ('challenge_range', models.PositiveIntegerField(default=3, help_text='Maksymalna liczba pozycji w górę, o które gracz może rzucić wyzwanie.')),
                ('initial_seeding', models.CharField(choices=[('RANDOM', 'Losowe'), ('MANUAL', 'Ręczne')], default='RANDOM', help_text='Sposób początkowego ustawienia graczy na drabince.', max_length=10)),
            ],
            options={
                'verbose_name': 'Konfiguracja Drabinki',
                'verbose_name_plural': 'Konfiguracje Drabinki',
            },
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tournament_type',
            field=models.CharField(choices=[('SGL', 'Puchar - pojedyncza eliminacja'), ('DBL', 'Puchar - drabinka pocieszenia'), ('RND', 'Liga (każdy z każdym)'), ('LDR', 'Lider - drabinka')], default='RND', help_text='Format w jakim odbywają się rozgrywki.', max_length=3),
        ),
        migrations.AlterField(
            model_name='tournamentsmatch',
            name='status',
            field=models.CharField(choices=[('WAI', 'Oczekuje'), ('SCH', 'Zaplanowany'), ('INP', 'W trakcie'), ('CMP', 'Zakończony'), ('WDR', 'Wycofany/Walkower'), ('CNC', 'Odwołany')], default='WAI', help_text='Status aktualnej rozgrywki.', max_length=3),
        ),
    ]
