# Generated by Django 5.2.6 on 2025-10-23 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0008_ladderconfig_alter_tournament_tournament_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ladderconfig',
            name='initial_seeding',
            field=models.CharField(choices=[('RANDOM', 'Losowe'), ('SEEDING', 'Według numeru rozstawienia (seed)')], default='SEEDING', help_text='Sposób początkowego ustawienia graczy na drabince po zamknięciu rejestracji.', max_length=10),
        ),
        migrations.CreateModel(
            name='ChallengeRejection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('challenger_participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges_rejected', to='tournaments.participant')),
                ('rejecting_participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rejections_made', to='tournaments.participant')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rejections', to='tournaments.tournament')),
            ],
            options={
                'verbose_name': 'Odrzucenie Wyzwania',
                'verbose_name_plural': 'Odrzucenia Wyzwań',
                'db_table': 'tournament_challenge_rejections',
                'unique_together': {('tournament', 'rejecting_participant', 'challenger_participant')},
            },
        ),
    ]
