# Generated by Django 5.2.6 on 2025-10-30 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0009_alter_ladderconfig_initial_seeding_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='tournament_type',
            field=models.CharField(choices=[('SGL', 'Puchar - pojedyncza eliminacja'), ('RND', 'Liga (każdy z każdym)'), ('LDR', 'Lider - drabinka')], default='RND', help_text='Format w jakim odbywają się rozgrywki.', max_length=3),
        ),
    ]
