# Generated by Django 5.2.6 on 2025-11-01 23:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0010_alter_tournament_tournament_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchScoreHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now_add=True, help_text='Data i godzina aktualizacji wyniku.')),
                ('set1_p1_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('set1_p2_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('set2_p1_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('set2_p2_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('set3_p1_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('set3_p2_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('match', models.ForeignKey(help_text='Mecz, którego dotyczy wpis historii.', on_delete=django.db.models.deletion.CASCADE, related_name='score_history', to='tournaments.tournamentsmatch')),
                ('updated_by', models.ForeignKey(help_text='Użytkownik, który zaktualizował wynik.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historia Wyniku Meczu',
                'verbose_name_plural': 'Historie Wyników Meczów',
                'db_table': 'tournament_match_score_history',
                'ordering': ['-updated_at'],
            },
        ),
    ]
