# Generated by Django 5.2.6 on 2025-11-04 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0001_initial'),
        ('tournaments', '0011_matchscorehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournaments', to='courts.tennisfacility', verbose_name='Obiekt tenisowy'),
        ),
    ]
