# Generated by Django 5.2.6 on 2025-11-05 12:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0012_tournament_facility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roundrobinconfig',
            name='points_for_gem_win',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.1'), help_text='Liczba punktów za wygrany gem.', max_digits=5),
        ),
        migrations.AlterField(
            model_name='roundrobinconfig',
            name='points_for_loss',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Liczba punktów za przegrany mecz.', max_digits=5),
        ),
        migrations.AlterField(
            model_name='roundrobinconfig',
            name='points_for_set_win',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Liczba punktów za wygrany set.', max_digits=5),
        ),
        migrations.AlterField(
            model_name='roundrobinconfig',
            name='points_for_win',
            field=models.DecimalField(decimal_places=2, default=Decimal('3.00'), help_text='Liczba punktów za wygrany mecz.', max_digits=5),
        ),
    ]
