# Generated by Django 5.2.6 on 2025-11-05 12:59

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0013_alter_roundrobinconfig_points_for_gem_win_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roundrobinconfig',
            name='points_for_set_loss',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Liczba punktów za przegrany set.', max_digits=5),
        ),
    ]
