# Generated by Django 5.2.6 on 2025-11-07 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0014_roundrobinconfig_points_for_set_loss'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='rank',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3')], default=1, verbose_name='Ranga turnieju'),
        ),
    ]
