# Generated by Django 5.2.6 on 2025-11-08 01:01

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0015_tournament_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roundrobinconfig',
            name='points_for_loss',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Liczba punktów za przegrany mecz.', max_digits=5),
        ),
        migrations.AlterField(
            model_name='roundrobinconfig',
            name='points_for_set_win',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.50'), help_text='Liczba punktów za wygrany set.', max_digits=5),
        ),
        migrations.AlterField(
            model_name='roundrobinconfig',
            name='points_for_win',
            field=models.DecimalField(decimal_places=2, default=Decimal('2.00'), help_text='Liczba punktów za wygrany mecz.', max_digits=5),
        ),
        migrations.AlterField(
            model_name='roundrobinconfig',
            name='tie_breaker_priority',
            field=models.CharField(choices=[('HEAD', 'Bezpośrednie spotkanie'), ('SETS', 'Bilans setów'), ('GAMES', 'Bilans gemów')], default='GAMES', help_text='Główne kryterium decydujące o kolejności w przypadku równej liczby punktów.', max_length=5),
        ),
    ]
