# Generated by Django 5.2.8 on 2026-04-05 10:24

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0017_tournament_winner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AmericanoConfig',
            fields=[
                ('tournament', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='americano_config', serialize=False, to='tournaments.tournament')),
                ('max_participants', models.IntegerField(default=16, help_text='Maksymalna liczba graczy. Powinna być wielokrotnością 4.')),
                ('points_per_match', models.PositiveIntegerField(default=32, help_text='Suma punktów do zdobycia w każdym meczu (np. 32, 48).')),
                ('number_of_rounds', models.PositiveIntegerField(default=7, help_text='Liczba rund do rozegrania w turnieju.')),
                ('scheduling_type', models.CharField(choices=[('STATIC', 'Americano (stały harmonogram)'), ('DYNAMIC', 'Mexicano (dynamiczne kojarzenie co rundę)')], default='STATIC', help_text='Sposób kojarzenia graczy w pary i mecze.', max_length=10)),
            ],
            options={
                'verbose_name': 'Konfiguracja Americano',
                'verbose_name_plural': 'Konfiguracje Americano',
            },
        ),
        migrations.CreateModel(
            name='SwissSystemConfig',
            fields=[
                ('max_participants', models.IntegerField(default=16, help_text='Maksymalna liczba graczy/zespołów.')),
                ('sets_to_win', models.IntegerField(default=2, help_text='Liczba setów, które należy wygrać, aby wygrać mecz (np. 1 z 2 lub 2 z 3).')),
                ('games_per_set', models.IntegerField(default=6, help_text='Liczba gemów wymaganych do wygrania seta (standardowo do 6 gemów z przewagą 2).')),
                ('tournament', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='swiss_system_config', serialize=False, to='tournaments.tournament')),
                ('initial_seeding', models.CharField(choices=[('RANDOM', 'Losowe'), ('SEEDING', 'Według rankingu (seed) - Najsilniejszy z najsłabszym')], default='SEEDING', help_text='Sposób parowania w pierwszej rundzie.', max_length=10)),
            ],
            options={
                'verbose_name': 'Konfiguracja Systemu Szwajcarskiego',
                'verbose_name_plural': 'Konfiguracje Systemu Szwajcarskiego',
            },
        ),
        migrations.RemoveField(
            model_name='eliminationconfig',
            name='is_seeded',
        ),
        migrations.AddField(
            model_name='eliminationconfig',
            name='initial_seeding',
            field=models.CharField(choices=[('RANDOM', 'Losowe'), ('SEEDING', 'Według rankingu (seed) - Najsilniejszy z najsłabszym')], default='SEEDING', help_text='Sposób parowania w pierwszej rundzie.', max_length=10),
        ),
        migrations.AddField(
            model_name='tournamentsmatch',
            name='participant3',
            field=models.ForeignKey(blank=True, help_text='Trzeci uczestnik/zespół (dla debla/americano).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_p3', to='tournaments.participant'),
        ),
        migrations.AddField(
            model_name='tournamentsmatch',
            name='participant4',
            field=models.ForeignKey(blank=True, help_text='Czwarty uczestnik/zespół (dla debla/americano).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_p4', to='tournaments.participant'),
        ),
        migrations.AlterField(
            model_name='roundrobinconfig',
            name='points_for_supertiebreak_loss',
            field=models.DecimalField(decimal_places=2, default=Decimal('-0.05'), help_text='Liczba punktów za przegrany super tie-break.', max_digits=3),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tournament_type',
            field=models.CharField(choices=[('SGL', 'Puchar - pojedyncza eliminacja'), ('DBE', 'Puchar - podwójna eliminacja'), ('RND', 'Liga (każdy z każdym)'), ('LDR', 'Lider - drabinka'), ('AMR', 'Americano / Mexicano'), ('SWS', 'System Szwajcarski')], default='RND', help_text='Format w jakim odbywają się rozgrywki.', max_length=3),
        ),
        migrations.CreateModel(
            name='MatchReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(choices=[('👍', '👍')], max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='tournaments.tournamentsmatch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'unique_together': {('match', 'user', 'emoji')},
            },
        ),
    ]
