# Generated by Django 5.2.8 on 2026-05-23 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0018_americanoconfig_swisssystemconfig_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='is_ranked',
            field=models.BooleanField(default=True, help_text='Jeśli odznaczone, turniej nie wpływa na globalny ranking klasyfikacyjny.', verbose_name='Turniej rankingowy'),
        ),
    ]
