# Generated by Django 5.2.8 on 2026-05-23 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0019_add_is_ranked_to_tournament'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tournamentsmatch',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='tournamentsmatch',
            name='bracket_type',
            field=models.CharField(choices=[('W', 'Winners'), ('L', 'Losers'), ('GF', 'Grand Final')], default='W', help_text='Typ drabinki: Winners (domyślny), Losers, Grand Final. Używane w Double Elimination.', max_length=2),
        ),
        migrations.AlterUniqueTogether(
            name='tournamentsmatch',
            unique_together={('tournament', 'bracket_type', 'round_number', 'match_index')},
        ),
    ]
