# Generated by Django 5.2.8 on 2026-06-10 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0020_add_bracket_type_to_match'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matchreaction',
            options={'ordering': ['created_at'], 'verbose_name': 'Lajk Meczowy', 'verbose_name_plural': 'Lajki Meczowe'},
        ),
    ]
