# Generated by Django 5.1 on 2025-09-06 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerranking',
            name='history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='playerranking',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
