# Generated by Django 5.1 on 2025-09-11 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0002_playerranking_history_playerranking_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerranking',
            name='supertiebreaks_lost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerranking',
            name='supertiebreaks_won',
            field=models.IntegerField(default=0),
        ),
    ]
