# Generated by Django 5.2.6 on 2025-10-30 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0003_playerranking_supertiebreaks_lost_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlayerRanking',
        ),
    ]
