# Generated by Django 5.2.6 on 2025-11-07 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rankings', '0004_delete_playerranking'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentRankPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField(unique=True, verbose_name='Ranga turnieju')),
                ('participation_bonus', models.PositiveIntegerField(default=0, verbose_name='Bonus za udział')),
                ('match_win_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=5, verbose_name='Mnożnik za wygrany mecz')),
                ('set_win_multiplier', models.DecimalField(decimal_places=2, default=0.5, max_digits=5, verbose_name='Mnożnik za wygrany set')),
                ('set_loss_multiplier', models.DecimalField(decimal_places=2, default=-0.5, max_digits=5, verbose_name='Mnożnik za przegrany set')),
                ('game_win_multiplier', models.DecimalField(decimal_places=2, default=0.1, max_digits=5, verbose_name='Mnożnik za wygrany gem')),
                ('game_loss_multiplier', models.DecimalField(decimal_places=2, default=-0.1, max_digits=5, verbose_name='Mnożnik za przegrany gem')),
            ],
        ),
    ]
