# Generated by Django 5.2.8 on 2026-04-05 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0005_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_type', models.CharField(default='SNG', max_length=3)),
                ('season', models.PositiveIntegerField(blank=True, null=True)),
                ('points', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('position', models.IntegerField(default=0)),
                ('matches_won', models.IntegerField(default=0)),
                ('matches_lost', models.IntegerField(default=0)),
                ('matches_played', models.IntegerField(default=0)),
                ('sets_won', models.IntegerField(default=0)),
                ('sets_lost', models.IntegerField(default=0)),
                ('games_won', models.IntegerField(default=0)),
                ('games_lost', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ranking', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'player_rankings',
                'ordering': ('-points', '-matches_won', '-sets_won'),
                'unique_together': {('user', 'match_type', 'season')},
            },
        ),
    ]
