# Generated by Django 5.2.8 on 2026-06-09 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0007_alter_playerranking_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankingCalculationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_run', models.DateTimeField(auto_now_add=True, verbose_name='Ostatnia aktualizacja')),
                ('next_run', models.DateTimeField(verbose_name='Kolejna aktualizacja')),
            ],
            options={
                'verbose_name': 'Metadane aktualizacji rankingu',
                'verbose_name_plural': 'Metadane aktualizacji rankingów',
                'db_table': 'ranking_calculation_info',
            },
        ),
    ]
