# Generated by Django 5.2.8 on 2026-06-10 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0008_rankingcalculationinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playerranking',
            options={'ordering': ('-points', '-matches_won', '-sets_won'), 'verbose_name': 'Aktualny Ranking', 'verbose_name_plural': 'Aktualny Ranking'},
        ),
        migrations.AlterModelOptions(
            name='tournamentrankpoints',
            options={'verbose_name': 'Bonus za Rangi', 'verbose_name_plural': 'Bonusy za Rangi'},
        ),
    ]
