"""
Django settings for tracker project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Wczytaj zmienne środowiskowe z pliku .env (głównie dla lokalnego developmentu)
load_dotenv(os.path.join(BASE_DIR, '.env'))

# Pobierz tryb środowiska (development lub production)
DJANGO_ENV = os.getenv('DJANGO_ENV', 'production') # Domyślnie 'production'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')
FIELD_ENCRYPTION_KEY = os.getenv('FIELD_ENCRYPTION_KEY')

# Ustawienia zależne od środowiska
if DJANGO_ENV == 'development':
    DEBUG = True
    ALLOWED_HOSTS = ['127.0.0.1', 'localhost', '10.0.2.2', '192.168.0.171']
    # Ustawienia SSL/Security wyłączone dla developmentu
    SECURE_HSTS_SECONDS = 0
    SECURE_HSTS_INCLUDE_SUBDOMAINS = False
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    SECURE_HSTS_PRELOAD = False
    # Ustawienia dla Django Debug Toolbar
    INTERNAL_IPS = ['127.0.0.1']
else: # Ustawienia produkcyjne
    DEBUG = False
    ALLOWED_HOSTS = ["tennisclub.ovh", "www.tennisclub.ovh", "tennis-club.fun", "www.tennis-club.fun", "tennis.mediprima.pl", '89.78.213.129']
    # Zabezpieczenie SSL
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_PRELOAD = True
    CSRF_TRUSTED_ORIGINS = [
    "https://tennisclub.ovh",
    "https://www.tennisclub.ovh",
    ]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.sitemaps',
    'django.contrib.humanize',
    'django_q',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'encrypted_model_fields',
    'notifications',
    'widget_tweaks',
    'chats',
    'apps',
    'apps.home',
    'apps.courts',
    'apps.friends',
    'apps.users',
    'apps.matches',
    'apps.rankings',
    'apps.tournaments',
    'apps.activities',
    'apps.feedback',
    'apps.news',
    'rest_framework',
    # 'apps.api',
]

SITE_ID = 2

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        }
    }
}

# Wyłącz automatyczną rejestrację, aby wymusić ustawienie hasła
SOCIALACCOUNT_LOGIN_ON_GET = True

# Ustawienia allauth dla logowania przez email i uproszczenia rejestracji
# Umożliwienie logowania za pomocą nazwy użytkownika lub adresu e-mail.
ACCOUNT_LOGIN_METHODS = ['username', 'email']
ACCOUNT_SIGNUP_FIELDS = []
SOCIALACCOUNT_ADAPTER = 'apps.users.adapters.CustomSocialAccountAdapter'
SOCIALACCOUNT_FORMS = {'signup': 'apps.users.forms.CustomSocialSignupForm'}
SOCIALACCOUNT_AUTO_SIGNUP = False

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'apps.home.middleware.BlockBotsMiddleware', # Blokowanie botów na początku
    'django.contrib.sessions.middleware.SessionMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'apps.home.middleware.ActiveUserMiddleware',
]

# Dodaj Debug Toolbar Middleware tylko w trybie deweloperskim
if DJANGO_ENV == 'development':
    MIDDLEWARE.insert(0, 'debug_toolbar.middleware.DebugToolbarMiddleware')

ROOT_URLCONF = 'core.urls'
LOGIN_URL = '/users/login/'
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/users/login/"
TEMPLATES_DIR = os.path.join(BASE_DIR, "templates")  # ROOT dir for templates


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATES_DIR],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],           
        },        
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME', 'tennis_club'),
        'USER': os.getenv('DB_USER', 'tennis_user'),
        'PASSWORD': os.getenv('DB_PASSWORD', ''),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = []


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'pl'

TIME_ZONE = 'Europe/Warsaw'

USE_I18N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Katalog, w którym Django będzie szukał globalnych plików statycznych
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Katalog, do którego `collectstatic` zbierze wszystkie pliki na produkcji
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Ustawienia dla plików mediów (zdjęć)
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Sesja pozostaje aktywna aż do wylogowania
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_SAVE_EVERY_REQUEST = True
# Czas trwania sesji (w sekundach) - 30 dni
SESSION_COOKIE_AGE = 30 * 24 * 60 * 60

# Cache configuration
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}

# VAPID configuration for push notifications
VAPID_PUBLIC_KEY = os.getenv('VAPID_PUBLIC_KEY')
VAPID_PRIVATE_KEY = os.getenv('VAPID_PRIVATE_KEY')

# --- LOGGING CONFIGURATION ---

# Ensure logs directory exists
LOG_DIR = os.path.join(BASE_DIR, 'logs')
if not os.path.exists(LOG_DIR):
    os.makedirs(LOG_DIR)

# List of apps to log separately
LOGGED_APPS = [
    'activities', 'api', 'courts', 'feedback', 'friends', 
    'home', 'matches', 'news', 'rankings', 'tournaments', 'users'
]

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'filters': {
        'add_ip_address': {
            '()': 'django.utils.log.CallbackFilter',
            'callback': lambda record: setattr(record, 'ip', getattr(record, 'request', None) and getattr(record.request, 'META', {}).get('REMOTE_ADDR', '-') or '-') or True,
        },
    },
    'formatters': {
        'verbose': {
            'format': '{asctime} [{levelname}] [IP: {ip}] {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'django.log'),
            'formatter': 'verbose',
            'encoding': 'utf-8',
            'filters': ['add_ip_address'],
        },
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
            'filters': ['add_ip_address'],
        },
    },
    'loggers': {
        '': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': True,
        },
        'django.utils.autoreload': {
            'handlers': ['file', 'console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'mysql.connector': {
            'handlers': ['file', 'console'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
}

# Dynamically execute logging setup for apps
for app in LOGGED_APPS:
    LOGGING['handlers'][app] = {
        'level': 'INFO',
        'class': 'logging.FileHandler',
        'filename': os.path.join(LOG_DIR, f'{app}.log'),
        'formatter': 'verbose',
        'encoding': 'utf-8',
        'filters': ['add_ip_address'],
    }
    LOGGING['loggers'][f'apps.{app}'] = {
        'handlers': [app, 'console'],
        'level': 'INFO',
        'propagate': False,
    }

# Dodaj aplikację Debug Toolbar tylko w trybie deweloperskim
if DJANGO_ENV == 'development':
    INSTALLED_APPS.append('debug_toolbar')

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        # Umożliwia korzystanie z logowania sesją w przeglądarkowym API
        'rest_framework.authentication.SessionAuthentication',
        # Główna metoda uwierzytelniania dla aplikacji klienckich
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

from datetime import timedelta

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
}

# settings.py (na końcu pliku)
Q_CLUSTER = {
    # Podstawowe ustawienia
    'name': 'TennisClubCluster',
    'label': 'Django Q',
    'orm': 'default',

    # Ustawienia Workerów (Kluczowe dla wydajności)
    'workers': 4,  # Utrzymane: Dobra wartość startowa, jeśli masz 4 rdzenie CPU lub więcej.
    'recycle': 200,  # Zmienione: Mniejsza wartość dla lepszego zarządzania pamięcią.
    'timeout': 360,  # Zmienione: Zwiększono timeout, aby uniknąć przedwczesnego przerywania dłuższych zadań.
    'retry': 420,  # Dodane: Czas ponowienia zadania (timeout + 60s) dla zapewnienia stabilności.

    # Ustawienia Kolejkowania i Optymalizacji
    'compress': True,  # Utrzymane: Dobra praktyka, zmniejsza rozmiar danych w kolejce.
    'save_limit': 0,   # Zmienione: Zmieniono na 0, aby zapisywać wszystkie wyniki (ważne dla debugowania).
    'queue_limit': 1000, # Zmienione: Zwiększono limit na wypadek nagłego wzrostu liczby zadań.
    'cpu_affinity': 1, # Utrzymane: Użycie 1 rdzenia na proces roboczy.

    # Nowe/Zmienione Ustawienia dla Stabilności
    'catch_up': True, # Dodane: Zapewnia, że workerzy wznowią pracę nad nieukończonymi zadaniami po awarii.
    'log_level': 'INFO', # Dodane: Ułatwia monitorowanie w logach.
}
