# Generated by Django 5.2.8 on 2026-04-05 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.CharField(max_length=255, verbose_name='Wzorzec URL')),
                ('description', models.TextField(blank=True, verbose_name='Opis (np. dlaczego blokujemy)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktywny')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data dodania')),
            ],
            options={
                'verbose_name': 'Zablokowany Wzorzec',
                'verbose_name_plural': 'Zablokowane Wzorce',
                'ordering': ['-created_at'],
            },
        ),
    ]
