# Generated by Django 5.2.8 on 2026-06-06 22:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=255, verbose_name='Nazwa użytkownika')),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True, verbose_name='Adres IP')),
                ('user_agent', models.TextField(blank=True, default='', verbose_name='User Agent')),
                ('status', models.CharField(choices=[('success', 'Sukces'), ('failed', 'Niepowodzenie')], max_length=10, verbose_name='Status')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Czas zdarzenia')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name': 'Próba logowania',
                'verbose_name_plural': 'Próby logowania',
                'ordering': ['-timestamp'],
            },
        ),
    ]
