# Generated by Django 5.2.8 on 2026-06-06 23:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_loginattempt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, verbose_name='Ścieżka URL')),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True, verbose_name='Adres IP')),
                ('user_agent', models.TextField(blank=True, default='', verbose_name='User Agent')),
                ('method', models.CharField(default='GET', max_length=10, verbose_name='Metoda HTTP')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40, null=True, verbose_name='Klucz sesji')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Czas wizyty')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name': 'Odsłona strony',
                'verbose_name_plural': 'Statystyki aktywności',
                'ordering': ['-timestamp'],
            },
        ),
    ]
