# Generated by Django 5.2.8 on 2026-04-05 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='Temat')),
                ('message', models.TextField(verbose_name='Wiadomość')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Adres e-mail (opcjonalnie)')),
                ('url', models.URLField(blank=True, max_length=2048, verbose_name='URL zgłoszenia')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data zgłoszenia')),
                ('status', models.CharField(choices=[('NEW', 'Nowe'), ('IN_PROGRESS', 'W trakcie'), ('RESOLVED', 'Rozwiązane'), ('CLOSED', 'Zamknięte')], default='NEW', max_length=20, verbose_name='Status')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adres IP')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name': 'Zgłoszenie',
                'verbose_name_plural': 'Zgłoszenia',
                'ordering': ['-created_at'],
            },
        ),
    ]
