# Generated by Django 5.1 on 2025-09-17 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
