# Generated by Django 5.2.8 on 2026-04-05 10:24

import django.db.models.deletion
import encrypted_model_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='garmin_login',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='garmin_password',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='garmin_sync_option',
            field=models.CharField(choices=[('TENNIS_ONLY', 'Tylko aktywności tenisowe'), ('ALL', 'Wszystkie aktywności')], default='TENNIS_ONLY', help_text='Wybierz, które aktywności synchronizować z Garmin Connect.', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
