# Generated by Django 5.2.8 on 2026-04-06 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_garmin_login_profile_garmin_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='garmin_login',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='garmin_password',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='garmin_sync_option',
        ),
    ]
