# Generated by Django 5.2.6 on 2025-11-02 11:09

import chats.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tournaments', '0011_matchscorehistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, verbose_name='Treść')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Znacznik czasu')),
                ('is_read', models.BooleanField(default=False, verbose_name='Przeczytana')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL, verbose_name='Odbiorca')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Nadawca')),
            ],
            options={
                'verbose_name': 'Wiadomość na czacie',
                'verbose_name_plural': 'Wiadomości na czacie',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ChatImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=chats.models.chat_image_upload_path, verbose_name='Obrazek')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Data wgrania')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='chats.chatmessage', verbose_name='Wiadomość')),
            ],
            options={
                'verbose_name': 'Obrazek w wiadomości',
                'verbose_name_plural': 'Obrazki w wiadomościach',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='TournamentMatchChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, verbose_name='Treść')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Znacznik czasu')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='tournaments.tournamentsmatch', verbose_name='Mecz')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_chat_messages', to=settings.AUTH_USER_MODEL, verbose_name='Nadawca')),
            ],
            options={
                'verbose_name': 'Wiadomość na czacie meczowym',
                'verbose_name_plural': 'Wiadomości na czacie meczowym',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TournamentMatchChatImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=chats.models.tournament_match_chat_image_upload_path, verbose_name='Obrazek')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Data wgrania')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='chats.tournamentmatchchatmessage', verbose_name='Wiadomość')),
            ],
            options={
                'verbose_name': 'Obrazek w czacie meczowym',
                'verbose_name_plural': 'Obrazki w czacie meczowym',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
