# Generated by Django 5.2.6 on 2025-11-04 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('court_number', models.PositiveIntegerField(verbose_name='Numer kortu')),
                ('surface', models.CharField(choices=[('Clay', 'Mączka'), ('Hard', 'Twarda'), ('Grass', 'Trawa'), ('Carpet', 'Dywanowa')], max_length=10, verbose_name='Nawierzchnia')),
                ('is_indoor', models.BooleanField(default=False, verbose_name='Kort kryty')),
            ],
            options={
                'verbose_name': 'Kort',
                'verbose_name_plural': 'Korty',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Czas rozpoczęcia')),
                ('end_time', models.DateTimeField(verbose_name='Czas zakończenia')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Oczekuje na zatwierdzenie'), ('CONFIRMED', 'Zatwierdzona'), ('REJECTED', 'Wymaga zmiany terminu'), ('CHANGED', 'Oczekuje na potwierdzenie zmiany terminu')], default='PENDING', max_length=10, verbose_name='Status')),
                ('court', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='courts.court', verbose_name='Kort')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='TennisFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nazwa obiektu')),
                ('address', models.CharField(max_length=300, verbose_name='Adres')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon kontaktowy')),
                ('surface', models.CharField(choices=[('Clay', 'Mączka'), ('Hard', 'Twarda'), ('Grass', 'Trawa'), ('Carpet', 'Dywanowa')], default='Clay', max_length=10, verbose_name='Nawierzchnia')),
                ('image', models.ImageField(blank=True, null=True, upload_to='facility_images/', verbose_name='Zdjęcie obiektu')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Właściciel')),
            ],
            options={
                'verbose_name': 'Obiekt tenisowy',
                'verbose_name_plural': 'Obiekty tenisowe',
            },
        ),
        migrations.AddField(
            model_name='court',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courts', to='courts.tennisfacility', verbose_name='Obiekt'),
        ),
        migrations.AlterUniqueTogether(
            name='court',
            unique_together={('facility', 'court_number')},
        ),
    ]
