# Generated by Django 5.2.8 on 2026-04-05 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tennisfacility',
            name='reservation',
            field=models.BooleanField(default=False, verbose_name='System rezerwacji'),
        ),
    ]
