# Generated by Django 5.2.8 on 2026-05-20 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0002_tennisfacility_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='series_id',
            field=models.UUIDField(blank=True, db_index=True, null=True, verbose_name='ID serii'),
        ),
    ]
