# Generated by Django 5.2.8 on 2026-06-10 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0003_add_series_id_to_reservation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['start_time'], 'verbose_name': 'Rezerwacja', 'verbose_name_plural': 'Rezerwacje'},
        ),
    ]
