# Generated by Django 5.2.8 on 2026-04-05 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID obiektu meczu')),
                ('activity_id', models.BigIntegerField(unique=True)),
                ('activity_name', models.CharField(max_length=255)),
                ('activity_type_key', models.CharField(blank=True, help_text="Klucz typu aktywności z Garmin, np. 'tennis_v2'", max_length=50, null=True)),
                ('start_time', models.DateTimeField(db_index=True)),
                ('duration', models.FloatField(help_text='In seconds')),
                ('distance', models.FloatField(help_text='In meters')),
                ('average_hr', models.IntegerField(blank=True, null=True)),
                ('max_hr', models.IntegerField(blank=True, null=True)),
                ('calories', models.IntegerField(blank=True, null=True)),
                ('tennis_data_fetched', models.BooleanField(default=False, help_text='Czy dane z aplikacji Tennis Studio zostały pomyślnie pobrane')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='Typ obiektu meczu')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garmin_activities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TennisData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_stats_side', models.CharField(blank=True, choices=[('L', 'Left'), ('P', 'Right')], help_text="Indicates if the activity owner's stats are on the 'Left' or 'Right' side of the Garmin data.", max_length=1, null=True)),
                ('score', models.CharField(blank=True, help_text='Wynik meczu, np. 6-4 6-3', max_length=50, null=True)),
                ('points', models.CharField(blank=True, help_text="Zdobyte punkty (np. w formacie '55:25')", max_length=50, null=True)),
                ('serving_points', models.CharField(blank=True, help_text='Punkty przy serwisie', max_length=50, null=True)),
                ('aces', models.CharField(blank=True, help_text='Asy serwisowe', max_length=50, null=True)),
                ('double_faults', models.CharField(blank=True, help_text='Podwójne błędy', max_length=50, null=True)),
                ('first_serve_percentage', models.CharField(blank=True, help_text='Procent pierwszego serwisu', max_length=50, null=True)),
                ('win_percentage_on_first_serve', models.CharField(blank=True, help_text='Procent wygranych po 1. serwisie', max_length=50, null=True)),
                ('win_percentage_on_second_serve', models.CharField(blank=True, help_text='Procent wygranych po 2. serwisie', max_length=50, null=True)),
                ('receiving_points', models.CharField(blank=True, help_text='Punkty przy odbiorze', max_length=50, null=True)),
                ('games', models.CharField(blank=True, help_text="Gemy (np. w formacie '12 : 2')", max_length=50, null=True)),
                ('breakpoints', models.CharField(blank=True, help_text="Punkty przełamania (np. w formacie '5/9 : 0/0')", max_length=50, null=True)),
                ('set_points', models.CharField(blank=True, help_text='Piłki setowe', max_length=50, null=True)),
                ('match_points', models.CharField(blank=True, help_text='Piłki meczowe', max_length=50, null=True)),
                ('sets_durations', models.CharField(blank=True, help_text='Czasy trwania setów', max_length=100, null=True)),
                ('winners', models.CharField(blank=True, help_text='Uderzenia wygrywające', max_length=50, null=True)),
                ('unforced_errors', models.CharField(blank=True, help_text='Niewymuszone błędy', max_length=50, null=True)),
                ('activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tennis_data', to='activities.activity')),
            ],
        ),
    ]
