# Generated by Django 5.1 on 2025-09-10 19:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='offlinefriend',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='onlinefriend',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='offlinefriend',
            constraint=models.UniqueConstraint(fields=('user', 'first_name', 'last_name'), name='unique_offline_friend'),
        ),
        migrations.AddConstraint(
            model_name='onlinefriend',
            constraint=models.UniqueConstraint(fields=('user', 'friend'), name='unique_online_friend'),
        ),
    ]
