# Generated by Django 5.2.6 on 2025-11-01 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0003_rename_onlinefriend_friend_remove_offlinefriend_user_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='friend',
            name='unique_online_friend',
        ),
    ]
