# Generated by Django 5.2.8 on 2026-06-10 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0005_friendrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friend',
            options={'verbose_name': 'Znajomy', 'verbose_name_plural': 'Znajomi'},
        ),
        migrations.AlterModelOptions(
            name='friendrequest',
            options={'verbose_name': 'Zaproszenie do znajomych', 'verbose_name_plural': 'Zaproszenia do znajomych'},
        ),
    ]
