# Generated by Django 5.1 on 2025-09-18 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_rename_notification_notifications'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='notifications',
            table='notifications',
        ),
    ]
