# Generated by Django 5.2.8 on 2026-05-30 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notifications_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='target_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
