# Generated by Django 5.2.8 on 2026-06-02 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_notifications_foundation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationpreference',
            name='event_type',
            field=models.CharField(choices=[('generic', 'Ogólne'), ('court.reservation.created', 'Nowa rezerwacja kortu'), ('court.reservation.accepted', 'Rezerwacja zaakceptowana'), ('court.reservation.rejected', 'Rezerwacja odrzucona'), ('court.reservation.cancelled', 'Rezerwacja anulowana'), ('tournament.created', 'Turniej utworzony'), ('tournament.started', 'Turniej rozpoczęty'), ('tournament.finished', 'Turniej zakończony'), ('tournament.cancelled', 'Turniej anulowany'), ('tournament.participant.added', 'Dodano uczestnika'), ('tournament.match.score_entered', 'Wynik meczu wpisany'), ('tournament.match.walkover', 'Walkover'), ('tournament.ladder.challenge_sent', 'Wyzwanie wysłane'), ('tournament.ladder.challenge_accepted', 'Wyzwanie zaakceptowane'), ('tournament.ladder.challenge_rejected', 'Wyzwanie odrzucone'), ('tournament.participant.joined', 'Uczestnik dołączył samodzielnie')], max_length=50),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='event_type',
            field=models.CharField(blank=True, choices=[('generic', 'Ogólne'), ('court.reservation.created', 'Nowa rezerwacja kortu'), ('court.reservation.accepted', 'Rezerwacja zaakceptowana'), ('court.reservation.rejected', 'Rezerwacja odrzucona'), ('court.reservation.cancelled', 'Rezerwacja anulowana'), ('tournament.created', 'Turniej utworzony'), ('tournament.started', 'Turniej rozpoczęty'), ('tournament.finished', 'Turniej zakończony'), ('tournament.cancelled', 'Turniej anulowany'), ('tournament.participant.added', 'Dodano uczestnika'), ('tournament.match.score_entered', 'Wynik meczu wpisany'), ('tournament.match.walkover', 'Walkover'), ('tournament.ladder.challenge_sent', 'Wyzwanie wysłane'), ('tournament.ladder.challenge_accepted', 'Wyzwanie zaakceptowane'), ('tournament.ladder.challenge_rejected', 'Wyzwanie odrzucone'), ('tournament.participant.joined', 'Uczestnik dołączył samodzielnie')], default='generic', max_length=50),
        ),
    ]
