# Generated by Django 5.2.8 on 2026-06-10 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_add_participant_removed_event_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationpreference',
            options={'ordering': ['event_type', 'channel'], 'verbose_name': 'Preferencja powiadomień', 'verbose_name_plural': 'Preferencje powiadomień'},
        ),
        migrations.AlterModelOptions(
            name='notifications',
            options={'ordering': ['-created_at'], 'verbose_name': 'Powiadomienie', 'verbose_name_plural': 'Powiadomienia'},
        ),
    ]
