# Generated by Django 5.2.8 on 2026-03-23 19:19

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.core.validators
import django.db.models.deletion
import django.db.models.functions.comparison
import v2_core.models.facilities
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('v2_core', '0001_initial_btree_gist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('tournament_type', models.CharField(choices=[('round_robin', 'Liga (ka|dy z ka|dym)'), ('single_elimination', 'Puchar (pojedyncza eliminacja)')], default='round_robin', max_length=20)),
                ('match_format', models.CharField(choices=[('singles', 'Singiel'), ('doubles', 'DebeB')], default='singles', max_length=10)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('registration_deadline', models.DateTimeField(blank=True, help_text='Termin zamkni\x19cia rejestracji', null=True)),
                ('status', models.CharField(choices=[('draft', 'Szkic'), ('registration', 'Rejestracja otwarta'), ('scheduled', 'Zaplanowany'), ('active', 'W trakcie'), ('finished', 'ZakoDczony'), ('cancelled', 'OdwoBany')], default='draft', max_length=20)),
                ('rank', models.PositiveIntegerField(default=1, help_text='Ranga turnieju (1-3, wy|szy = wi\x19cej punktĂłw)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('max_participants', models.PositiveIntegerField(default=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_tournaments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Turniej',
                'verbose_name_plural': 'Turnieje',
                'db_table': 'tournaments',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='TournamentRankPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField(help_text='Ranga turnieju (1-3)', unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('winner_points', models.IntegerField(default=100)),
                ('finalist_points', models.IntegerField(default=70)),
                ('semifinal_points', models.IntegerField(default=45)),
                ('quarterfinal_points', models.IntegerField(default=25)),
                ('participation_points', models.IntegerField(default=10)),
            ],
            options={
                'verbose_name': 'Punkty za rang\x19 turnieju',
                'db_table': 'tournament_rank_points',
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('default_surface', models.CharField(choices=[('clay', 'Mączka'), ('hard', 'Twarda'), ('grass', 'Trawa'), ('carpet', 'Dywanowa')], default='clay', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='facility_images/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_facilities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Obiekt tenisowy',
                'verbose_name_plural': 'Obiekty tenisowe',
                'db_table': 'facilities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(help_text='Numer kortu w obiekcie')),
                ('surface', models.CharField(choices=[('clay', 'Mączka'), ('hard', 'Twarda'), ('grass', 'Trawa'), ('carpet', 'Dywanowa')], max_length=10)),
                ('is_indoor', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courts', to='v2_core.facility')),
            ],
            options={
                'verbose_name': 'Kort',
                'verbose_name_plural': 'Korty',
                'db_table': 'courts',
                'ordering': ['facility', 'number'],
                'unique_together': {('facility', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(help_text='Nazwa wy[wietlana (auto z username lub custom)', max_length=100)),
                ('seed', models.PositiveIntegerField(blank=True, help_text='Numer rozstawienia', null=True)),
                ('status', models.CharField(choices=[('registered', 'Zarejestrowany'), ('active', 'Aktywny'), ('eliminated', 'Wyeliminowany'), ('withdrawn', 'Wycofany')], default='registered', max_length=20)),
                ('points', models.DecimalField(decimal_places=2, default=0, help_text='Punkty w tabeli (liga)', max_digits=10)),
                ('matches_won', models.IntegerField(default=0)),
                ('matches_lost', models.IntegerField(default=0)),
                ('sets_won', models.IntegerField(default=0)),
                ('sets_lost', models.IntegerField(default=0)),
                ('games_won', models.IntegerField(default=0)),
                ('games_lost', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('partner', models.ForeignKey(blank=True, help_text='Partner w deblu', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournament_partnerships', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Uczestnik turnieju',
                'verbose_name_plural': 'Uczestnicy turnieju',
                'db_table': 'tournament_participants',
                'ordering': ['-points', '-matches_won'],
            },
        ),
        migrations.CreateModel(
            name='TournamentConfig',
            fields=[
                ('tournament', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='config', serialize=False, to='v2_core.tournament')),
                ('sets_to_win', models.IntegerField(default=2, help_text='Liczba wygranych setĂłw potrzebna do wygranej')),
                ('games_per_set', models.IntegerField(default=6, help_text='Liczba gemĂłw do wygrania seta')),
                ('points_for_match_win', models.DecimalField(decimal_places=2, default=Decimal('3.00'), help_text='Punkty za wygrany mecz (liga)', max_digits=5)),
                ('points_for_match_loss', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Punkty za przegrany mecz (liga)', max_digits=5)),
                ('points_for_set_win', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Punkty za wygrany set (liga)', max_digits=5)),
                ('use_seeding', models.BooleanField(default=True, help_text='Czy u|ywa\x07 seedingu (ranking) w pierwszej rundzie')),
                ('third_place_match', models.BooleanField(default=True, help_text='Czy rozgrywa\x07 mecz o 3. miejsce')),
            ],
            options={
                'verbose_name': 'Konfiguracja turnieju',
                'db_table': 'tournament_configs',
            },
        ),
        migrations.AddField(
            model_name='tournament',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournaments', to='v2_core.facility'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_tournaments', to='v2_core.participant'),
        ),
        migrations.AddField(
            model_name='participant',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='v2_core.tournament'),
        ),
        migrations.CreateModel(
            name='TournamentMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField(default=1, help_text='Numer rundy (1=pierwsza, 2=\x07wier\x07finaB, etc.)')),
                ('match_number', models.PositiveIntegerField(default=1, help_text='Numer meczu w rundzie')),
                ('status', models.CharField(choices=[('waiting', 'Oczekuje'), ('scheduled', 'Zaplanowany'), ('in_progress', 'W trakcie'), ('completed', 'ZakoDczony'), ('walkover', 'Walkower')], default='waiting', max_length=20)),
                ('scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('set1_p1', models.IntegerField(blank=True, null=True)),
                ('set1_p2', models.IntegerField(blank=True, null=True)),
                ('set2_p1', models.IntegerField(blank=True, null=True)),
                ('set2_p2', models.IntegerField(blank=True, null=True)),
                ('set3_p1', models.IntegerField(blank=True, null=True)),
                ('set3_p2', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('court', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_matches', to='v2_core.court')),
                ('participant1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_p1', to='v2_core.participant')),
                ('participant2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_p2', to='v2_core.participant')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_matches', to='v2_core.tournament')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_matches', to='v2_core.participant')),
            ],
            options={
                'verbose_name': 'Mecz turniejowy',
                'verbose_name_plural': 'Mecze turniejowe',
                'db_table': 'tournament_matches',
                'ordering': ['round_number', 'match_number'],
            },
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Oczekuje'), ('accepted', 'Zaakceptowane'), ('rejected', 'Odrzucone')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_friend_requests', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_friend_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Zaproszenie do znajomych',
                'verbose_name_plural': 'Zaproszenia do znajomych',
                'db_table': 'friend_requests',
                'ordering': ['-created_at'],
                'unique_together': {('sender', 'receiver')},
            },
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_of', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Znajomość',
                'verbose_name_plural': 'Znajomości',
                'db_table': 'friendships',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='friendships_user_id_73bf33_idx'), models.Index(fields=['friend'], name='friendships_friend__0fa049_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('user', models.F('friend')), _negated=True), name='friendships_no_self_relation'), models.UniqueConstraint(django.db.models.functions.comparison.Least('user_id', 'friend_id'), django.db.models.functions.comparison.Greatest('user_id', 'friend_id'), name='friendships_unique_normalized_pair')],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_doubles', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('scheduled', 'Zaplanowany'), ('in_progress', 'W trakcie'), ('completed', 'Zakończony'), ('cancelled', 'Anulowany')], default='scheduled', max_length=20)),
                ('set1_p1', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('set1_p2', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('set2_p1', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('set2_p2', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('set3_p1', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('set3_p2', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('winner_side', models.CharField(blank=True, choices=[('p1', 'Player/Team 1'), ('p2', 'Player/Team 2')], max_length=2, null=True)),
                ('match_date', models.DateField()),
                ('description', models.CharField(default='Mecz towarzyski', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('court', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='v2_core.court')),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_p1', to=settings.AUTH_USER_MODEL)),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_p2', to=settings.AUTH_USER_MODEL)),
                ('player3', models.ForeignKey(blank=True, help_text='Partner player1 (debeł)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_p3', to=settings.AUTH_USER_MODEL)),
                ('player4', models.ForeignKey(blank=True, help_text='Partner player2 (debeł)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_p4', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mecz',
                'verbose_name_plural': 'Mecze',
                'db_table': 'matches',
                'ordering': ['-match_date'],
                'indexes': [models.Index(fields=['-match_date'], name='matches_match_d_fe43ce_idx'), models.Index(fields=['is_doubles'], name='matches_is_doub_ec700d_idx'), models.Index(fields=['status', 'match_date'], name='matches_status_23ee60_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('player1', models.F('player2')), _negated=True), name='matches_player1_ne_player2')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('info', 'Informacja'), ('match', 'Mecz'), ('tournament', 'Turniej'), ('reservation', 'Rezerwacja'), ('system', 'System')], default='info', max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('link', models.CharField(blank=True, help_text='URL do przekierowania po klikni\x19ciu', max_length=200)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Powiadomienie',
                'verbose_name_plural': 'Powiadomienia',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='notificatio_user_id_611c58_idx'), models.Index(fields=['user', 'is_read'], name='notificatio_user_id_a4dd5c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('image', models.ImageField(blank=True, default='default.png', upload_to='profile_pics')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('elo_rating', models.IntegerField(default=1200, help_text='Rating Elo gracza')),
                ('ranking_points', models.DecimalField(decimal_places=2, default=0, help_text='Punkty rankingowe z turniejów', max_digits=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil',
                'verbose_name_plural': 'Profile',
                'db_table': 'profiles',
                'indexes': [models.Index(fields=['-elo_rating'], name='profiles_elo_rat_61e7b1_idx'), models.Index(fields=['-ranking_points'], name='profiles_ranking_61610b_idx')],
            },
        ),
        migrations.CreateModel(
            name='RankingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('elo_rating', models.IntegerField()),
                ('ranking_points', models.DecimalField(decimal_places=2, max_digits=10)),
                ('position', models.PositiveIntegerField(help_text='Pozycja w rankingu klubowym', null=True)),
                ('total_matches', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranking_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historia rankingu',
                'verbose_name_plural': 'Historie rankingĂłw',
                'db_table': 'ranking_history',
                'ordering': ['-date', 'position'],
                'indexes': [models.Index(fields=['user', '-date'], name='ranking_his_user_id_cefac3_idx'), models.Index(fields=['date', 'position'], name='ranking_his_date_38f57e_idx')],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Oczekuje'), ('confirmed', 'Potwierdzona'), ('cancelled', 'Anulowana')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='v2_core.court')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rezerwacja',
                'verbose_name_plural': 'Rezerwacje',
                'db_table': 'reservations',
                'ordering': ['start_time'],
                'indexes': [models.Index(fields=['court', 'start_time'], name='reservation_court_i_9b4aba_idx'), models.Index(fields=['user', '-start_time'], name='reservation_user_id_f0d1b3_idx'), models.Index(fields=['status'], name='reservation_status_a87326_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='reservations_end_after_start'), django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('status__in', ['pending', 'confirmed'])), expressions=[(v2_core.models.facilities.TsTzRange('start_time', 'end_time', django.contrib.postgres.fields.ranges.RangeBoundary()), '&&'), ('court', '=')], name='reservations_no_overlap_per_court')],
            },
        ),
        migrations.AddIndex(
            model_name='tournament',
            index=models.Index(fields=['status'], name='tournaments_status_2bfcdf_idx'),
        ),
        migrations.AddIndex(
            model_name='tournament',
            index=models.Index(fields=['-start_date'], name='tournaments_start_d_01ccd9_idx'),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['tournament', '-points'], name='tournament__tournam_28566d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together={('tournament', 'user')},
        ),
        migrations.AddIndex(
            model_name='tournamentmatch',
            index=models.Index(fields=['tournament', 'status'], name='tournament__tournam_9dcd31_idx'),
        ),
        migrations.AddIndex(
            model_name='tournamentmatch',
            index=models.Index(fields=['scheduled_time'], name='tournament__schedul_9af14a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tournamentmatch',
            unique_together={('tournament', 'round_number', 'match_number')},
        ),
    ]
