# Generated by Django 5.2.8 on 2026-04-01 11:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v2_core', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rankinghistory',
            options={'ordering': ['-date', 'position'], 'verbose_name': 'Historia rankingu', 'verbose_name_plural': 'Historie rankingów'},
        ),
        migrations.AlterModelOptions(
            name='tournamentrankpoints',
            options={'ordering': ['rank'], 'verbose_name': 'Punkty za rangę turnieju', 'verbose_name_plural': 'Punkty za rangę turnieju'},
        ),
        migrations.RemoveField(
            model_name='tournamentmatch',
            name='participant1',
        ),
        migrations.RemoveField(
            model_name='tournamentmatch',
            name='participant2',
        ),
        migrations.RemoveField(
            model_name='tournamentmatch',
            name='winner',
        ),
        migrations.AddField(
            model_name='participant',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text='Data i godzina zatwierdzenia przez managera', null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='final_position',
            field=models.PositiveIntegerField(blank=True, help_text='Finalna pozycja w turnieju (1=zwycięzca)', null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='joined_at',
            field=models.DateTimeField(blank=True, help_text='Data i godzina zgłoszenia', null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='withdrawal_reason',
            field=models.TextField(blank=True, help_text='Powód wycofania się'),
        ),
        migrations.AddField(
            model_name='participant',
            name='withdrawn_at',
            field=models.DateTimeField(blank=True, help_text='Data i godzina wycofania się', null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, help_text='Data i godzina odwołania', null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='finished_at',
            field=models.DateTimeField(blank=True, help_text='Data i godzina faktycznego zakończenia', null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='min_participants',
            field=models.PositiveIntegerField(default=2, help_text='Minimalna liczba uczestników', validators=[django.core.validators.MinValueValidator(2)]),
        ),
        migrations.AddField(
            model_name='tournament',
            name='registration_mode',
            field=models.CharField(choices=[('auto', 'Automatyczne zatwierdzenie'), ('approval_required', 'Wymaga zatwierdzenia')], default='auto', help_text='Tryb akceptacji uczestników', max_length=20),
        ),
        migrations.AddField(
            model_name='tournament',
            name='registration_open_at',
            field=models.DateTimeField(blank=True, help_text='Data i godzina otwarcia zapisów', null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='Ostatnia osoba modyfikująca turniej', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_tournaments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tournament',
            name='visibility',
            field=models.CharField(choices=[('public', 'Publiczny'), ('private', 'Prywatny'), ('invite_only', 'Tylko zaproszenia')], default='public', help_text='Widoczność turnieju', max_length=20),
        ),
        migrations.AddField(
            model_name='tournamentmatch',
            name='bracket_position',
            field=models.PositiveIntegerField(blank=True, help_text='Pozycja w drabince (unikalna w obrębie turnieju)', null=True),
        ),
        migrations.AddField(
            model_name='tournamentmatch',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='Faktyczny czas zakończenia', null=True),
        ),
        migrations.AddField(
            model_name='tournamentmatch',
            name='loser_participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lost_tournament_matches', to='v2_core.participant'),
        ),
        migrations.AddField(
            model_name='tournamentmatch',
            name='player1_participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_player1', to='v2_core.participant'),
        ),
        migrations.AddField(
            model_name='tournamentmatch',
            name='player2_participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_player2', to='v2_core.participant'),
        ),
        migrations.AddField(
            model_name='tournamentmatch',
            name='source_match_1',
            field=models.ForeignKey(blank=True, help_text='Mecz źródłowy dla player1 (zwycięzca source_match_1 -> player1)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feeds_into_as_source1', to='v2_core.tournamentmatch'),
        ),
        migrations.AddField(
            model_name='tournamentmatch',
            name='source_match_2',
            field=models.ForeignKey(blank=True, help_text='Mecz źródłowy dla player2 (zwycięzca source_match_2 -> player2)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feeds_into_as_source2', to='v2_core.tournamentmatch'),
        ),
        migrations.AddField(
            model_name='tournamentmatch',
            name='walkover_reason',
            field=models.TextField(blank=True, help_text='Powód walkower (wycofanie, kontuzja, etc.)'),
        ),
        migrations.AddField(
            model_name='tournamentmatch',
            name='winner_participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_tournament_matches', to='v2_core.participant'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='link',
            field=models.CharField(blank=True, help_text='URL do przekierowania po kliknięciu', max_length=200),
        ),
        migrations.AlterField(
            model_name='participant',
            name='display_name',
            field=models.CharField(help_text='Nazwa wyświetlana (auto z username lub custom)', max_length=100),
        ),
        migrations.AlterField(
            model_name='participant',
            name='seed',
            field=models.PositiveIntegerField(blank=True, help_text='Numer rozstawienia', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='participant',
            name='status',
            field=models.CharField(choices=[('pending', 'Oczekuje'), ('confirmed', 'Potwierdzony'), ('waitlist', 'Lista rezerwowa'), ('withdrawn', 'Wycofany'), ('rejected', 'Odrzucony'), ('eliminated', 'Wyeliminowany'), ('winner', 'Zwycięzca')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='match_format',
            field=models.CharField(choices=[('singles', 'Singiel'), ('doubles', 'debel')], default='singles', max_length=10),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='rank',
            field=models.PositiveIntegerField(default=1, help_text='Ranga turnieju (1-3, wyższy = więcej punktów)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='registration_deadline',
            field=models.DateTimeField(blank=True, help_text='Termin zamknięcia rejestracji', null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='status',
            field=models.CharField(choices=[('draft', 'Szkic'), ('registration_open', 'Rejestracja otwarta'), ('registration_closed', 'Rejestracja zamknięta'), ('participants_confirmed', 'Skład zatwierdzony'), ('bracket_ready', 'Drabinka gotowa'), ('in_progress', 'W trakcie'), ('finished', 'Zakończony'), ('cancelled', 'Odwołany')], default='draft', max_length=25),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tournament_type',
            field=models.CharField(choices=[('round_robin', 'Liga (każdy z każdym)'), ('single_elimination', 'Puchar (pojedyncza eliminacja)')], default='round_robin', max_length=20),
        ),
        migrations.AlterField(
            model_name='tournamentconfig',
            name='games_per_set',
            field=models.IntegerField(default=6, help_text='Liczba gemów do wygrania seta'),
        ),
        migrations.AlterField(
            model_name='tournamentconfig',
            name='sets_to_win',
            field=models.IntegerField(default=2, help_text='Liczba wygranych setów potrzebna do wygranej'),
        ),
        migrations.AlterField(
            model_name='tournamentconfig',
            name='third_place_match',
            field=models.BooleanField(default=True, help_text='Czy rozgrywa mecz o 3. miejsce'),
        ),
        migrations.AlterField(
            model_name='tournamentconfig',
            name='use_seeding',
            field=models.BooleanField(default=True, help_text='Czy używa seedingu (ranking) w pierwszej rundzie'),
        ),
        migrations.AlterField(
            model_name='tournamentmatch',
            name='match_number',
            field=models.PositiveIntegerField(default=1, help_text='Numer meczu w rundzie (dla identyfikacji)'),
        ),
        migrations.AlterField(
            model_name='tournamentmatch',
            name='round_number',
            field=models.PositiveIntegerField(default=1, help_text='Numer rundy (1=pierwsza runda, wyższe=dalsze rundy)', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='tournamentmatch',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, help_text='Planowany czas rozpoczęcia', null=True),
        ),
        migrations.AlterField(
            model_name='tournamentmatch',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Zaplanowany'), ('ready', 'Gotowy'), ('in_progress', 'W trakcie'), ('completed', 'Zakończony'), ('walkover', 'Walkower'), ('cancelled', 'Odwołany')], default='scheduled', max_length=20),
        ),
        migrations.CreateModel(
            name='TournamentEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'Utworzenie turnieju'), ('registration_opened', 'Otwarcie zapisów'), ('registration_closed', 'Zamknięcie zapisów'), ('participant_joined', 'Zapis uczestnika'), ('participant_approved', 'Zatwierdzenie uczestnika'), ('participant_rejected', 'Odrzucenie uczestnika'), ('participant_withdrawn', 'Wycofanie uczestnika'), ('participants_confirmed', 'Zatwierdzenie składu'), ('bracket_generated', 'Wygenerowanie drabinki'), ('tournament_started', 'Start turnieju'), ('match_scheduled', 'Zaplanowanie meczu'), ('match_result', 'Wynik meczu'), ('match_walkover', 'Walkover'), ('tournament_finished', 'Zakończenie turnieju'), ('tournament_cancelled', 'Odwołanie turnieju'), ('ranking_points_awarded', 'Naliczenie punktów rankingowych')], max_length=30)),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Dodatkowe dane o zdarzeniu (JSON)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, help_text='Użytkownik wykonujący akcję (może być NULL dla akcji systemowych)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_actions', to=settings.AUTH_USER_MODEL)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_logs', to='v2_core.tournament')),
            ],
            options={
                'verbose_name': 'Log zdarzeń turniejowych',
                'verbose_name_plural': 'Logi zdarzeń turniejowych',
                'db_table': 'tournament_event_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tournament', '-created_at'], name='tournament__tournam_3cebdd_idx'), models.Index(fields=['event_type'], name='tournament__event_t_a818c5_idx')],
            },
        ),
        migrations.CreateModel(
            name='TournamentManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Właściciel'), ('manager', 'Manager')], default='manager', help_text='Rola w zarządzaniu turniejem', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managers', to='v2_core.tournament')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_tournaments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Manager turnieju',
                'verbose_name_plural': 'Managerowie turnieju',
                'db_table': 'tournament_managers',
                'indexes': [models.Index(fields=['tournament', 'user'], name='tournament__tournam_4f95ff_idx')],
                'unique_together': {('tournament', 'user')},
            },
        ),
    ]
