# Generated by Django 5.2.8 on 2026-04-03 08:00

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v2_core', '0003_alter_rankinghistory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentconfig',
            name='points_for_game_loss',
            field=models.DecimalField(decimal_places=2, default=Decimal('-0.10'), help_text='Kara za przegrany gem (liga)', max_digits=5),
        ),
        migrations.AddField(
            model_name='tournamentconfig',
            name='points_for_game_win',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.10'), help_text='Bonus za wygrany gem (liga)', max_digits=5),
        ),
        migrations.AddField(
            model_name='tournamentconfig',
            name='points_for_set_loss',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Kara za przegrany set (liga)', max_digits=5),
        ),
        migrations.AddField(
            model_name='tournamentconfig',
            name='points_for_tiebreak_point_loss',
            field=models.DecimalField(decimal_places=2, default=Decimal('-0.05'), help_text='Kara za punkt w Super Tie-breaku (liga)', max_digits=5),
        ),
        migrations.AddField(
            model_name='tournamentconfig',
            name='points_for_tiebreak_point_win',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.05'), help_text='Bonus za punkt w Super Tie-breaku (liga)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='tournamentconfig',
            name='points_for_match_loss',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Punkty za przegrany mecz (liga)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='tournamentconfig',
            name='points_for_match_win',
            field=models.DecimalField(decimal_places=2, default=Decimal('2.00'), help_text='Punkty za wygrany mecz (liga)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='tournamentconfig',
            name='points_for_set_win',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.50'), help_text='Bonus za wygrany set (liga)', max_digits=5),
        ),
    ]
