# Generated by Django 5.2.8 on 2026-04-03 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v2_core', '0004_tournamentconfig_points_for_game_loss_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentconfig',
            name='tiebreaker_criteria',
            field=models.CharField(choices=[('head_to_head', 'Bezpośrednie spotkanie'), ('game_difference', 'Bilans gemów'), ('set_difference', 'Bilans setów')], default='head_to_head', help_text='Główne kryterium decydujące o kolejności w przypadku równej liczby punktów', max_length=20),
        ),
    ]
