# Generated by Django 5.1 on 2025-09-06 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p1_set1', models.IntegerField()),
                ('p1_set2', models.IntegerField()),
                ('p1_set3', models.IntegerField()),
                ('p2_set1', models.IntegerField()),
                ('p2_set2', models.IntegerField()),
                ('p2_set3', models.IntegerField()),
                ('match_double', models.BooleanField(default=False)),
                ('match_offline', models.BooleanField(default=False)),
                ('description', models.CharField(default='TOWARZYSKIE', max_length=100)),
                ('match_date', models.DateField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('p1', models.ForeignKey(db_column='p1', on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_p1', to=settings.AUTH_USER_MODEL)),
                ('p2', models.ForeignKey(db_column='p2', on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_p2', to=settings.AUTH_USER_MODEL)),
                ('p3', models.ForeignKey(blank=True, db_column='p3', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_p3', to=settings.AUTH_USER_MODEL)),
                ('p4', models.ForeignKey(blank=True, db_column='p4', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_p4', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'matches',
                'indexes': [models.Index(fields=['match_date'], name='matches_match_d_701e65_idx'), models.Index(fields=['match_double', 'match_offline'], name='matches_match_d_873a35_idx')],
            },
        ),
    ]
