# Generated by Django 5.1 on 2025-09-06 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='p1_set1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='p1_set2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='p1_set3',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='p2_set1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='p2_set2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='p2_set3',
            field=models.IntegerField(default=0),
        ),
    ]
