# Generated by Django 5.2.6 on 2025-11-01 12:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_alter_match_p1_set1_alter_match_p1_set2_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='match',
            name='matches_match_d_873a35_idx',
        ),
        migrations.RemoveField(
            model_name='match',
            name='match_offline',
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['match_double'], name='matches_match_d_cc552d_idx'),
        ),
    ]
