# Generated by Django 5.2.8 on 2026-04-05 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_remove_match_matches_match_d_873a35_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='p1_set2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='p1_set3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='p2_set2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='p2_set3',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
