# Generated by Django 5.2.8 on 2026-04-29 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_alter_match_p1_set2_alter_match_p1_set3_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, db_column='confirmed_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_matches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='match',
            name='reported_by',
            field=models.ForeignKey(blank=True, db_column='reported_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_matches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='match',
            name='score_status',
            field=models.CharField(choices=[('PENDING', 'Oczekuje na potwierdzenie'), ('CONFIRMED', 'Potwierdzony')], default='CONFIRMED', max_length=10),
        ),
    ]
