# Generated by Django 5.2.8 on 2026-06-10 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0005_add_score_status_reported_confirmed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name': 'Mecz', 'verbose_name_plural': 'Mecze'},
        ),
    ]
