# Generated by Django 5.2.8 on 2026-06-10 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0006_alter_match_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name': 'Mecz Towarzyski', 'verbose_name_plural': 'Mecze Towarzyskie'},
        ),
    ]
